# Generated by Django 4.2 on 2025-02-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MakeupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank', models.FloatField()),
                ('skin_type', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SkincareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Skin_type', models.CharField(max_length=100)),
                ('Product', models.CharField(max_length=200)),
                ('Concern', models.CharField(max_length=200)),
                ('product_url', models.URLField()),
                ('product_pic', models.URLField()),
            ],
        ),
        migrations.AddIndex(
            model_name='skincareproduct',
            index=models.Index(fields=['Skin_type'], name='products_sk_Skin_ty_2c0d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='skincareproduct',
            index=models.Index(fields=['Concern'], name='products_sk_Concern_cc6493_idx'),
        ),
        migrations.AddIndex(
            model_name='makeupproduct',
            index=models.Index(fields=['skin_type'], name='products_ma_skin_ty_fc269a_idx'),
        ),
        migrations.AddIndex(
            model_name='makeupproduct',
            index=models.Index(fields=['rank'], name='products_ma_rank_7a95f2_idx'),
        ),
    ]
