# Generated by Django 4.2 on 2025-03-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('title_href', models.URLField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('noofratings', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MakeupProduct',
        ),
        migrations.AddIndex(
            model_name='cosmeticproduct',
            index=models.Index(fields=['category'], name='products_co_categor_b44b82_idx'),
        ),
        migrations.AddIndex(
            model_name='cosmeticproduct',
            index=models.Index(fields=['subcategory'], name='products_co_subcate_edba03_idx'),
        ),
        migrations.AddIndex(
            model_name='cosmeticproduct',
            index=models.Index(fields=['brand'], name='products_co_brand_253344_idx'),
        ),
        migrations.AddIndex(
            model_name='cosmeticproduct',
            index=models.Index(fields=['rating'], name='products_co_rating_263e63_idx'),
        ),
    ]
